### ISSUE TITLE
Work In Progress - How to get measure list?

### ISSUE THREAD

**Issue by Spomky** [PointerEvent/bosch-plr-demo#2]
Hi,

In addition to the PR #1, I continue working on the script.
Please have a look at the branch https://github.com/Spomky-Labs/bosch-plr-demo/tree/features/better-message-handling

I added CRC8 verification and other features.
The messages are completely desctructured and it is now possible to recognize a single distance, angle, area, volume and more (the UI is not up to date).

The main problem now is to handle the responses when a measure is triggered.
The documentation is not very useful here. What I would like to do is
* change the device mode (looks good so far)
* to trigger a measure (already available, just tweaked a bit that part)
* get the measure (I am lost here ฅʕ•̫͡•ʔฅ)

Do you know how to retreive the measures?
Section 5.2 *Measurement list handling* is written as follows:

> For SPAD platforms using ExchangeDataContainer commands.
Command 83 “Get user settings” delivers MeasListLastUsedIndex.
The complete MeasList needs to be received stepwise index by index using command 85 “Exchange data container” with RemoteCtrlCmd 58 “GetMeasListEntryByIndex”. Potential details of each measurement (e.g. Volume part 1) can be requested using “request measurement part value” different to 0.

Unfortunately, I cannot have a list of values.
Do you have any idea?

**Comment by PointerEvent** [comment]
Did you find the solution for this?

**Comment by Spomky** [comment]
No, I did not.
I decided to trigger the measurement from the device and not the web application.
I will try finding a solution later. I close the issue as no move at the moment.
